name: Release

# Controls when the action will run. 
on:
  release:
    types: 
      - published
      - edited
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 
  
jobs: 
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.nbgv.outputs.NuGetPackageVersion }}
    steps:
      - uses: actions/checkout@v2 
        with: 
          fetch-depth: 0
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2 
        with:
          dotnet-version: 5.0.x   

      - uses: dotnet/nbgv@master
        id: nbgv 
      
      - name: Build 
        run: dotnet build
        working-directory: src/SimpleToggle 

  package-core:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0 
         
      - name: Publish Core
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/SimpleToggle/SimpleToggle.Core/SimpleToggle.Core.csproj
          PACKAGE_NAME: SimpleToggle 
          VERSION_STATIC: ${{ needs.build.outputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          #INCLUDE_SYMBOLS: true # Action currently fails when including symbols

  package-aws-sources:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0     
          
      - name: Publish AWS Source
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/SimpleToggle/SimpleToggle.Sources.AWS/
          PACKAGE_NAME: SimpleToggle.AWS
          VERSION_STATIC: ${{ needs.build.outputs.version }}
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          #INCLUDE_SYMBOLS: true
